export const UPDATE_COLLECTION = 'UPDATE_COLLECTION';
export const FECTH_COLLECTIONS_START = 'FECTH_COLLECTIONS_START';
export const FECTH_COLLECTIONS_SUCCESS = 'FECTH_COLLECTIONS_SUCCESS';
export const FECTH_COLLECTIONS_FAILURE = 'FECTH_COLLECTIONS_FAILURE';
